server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy vers le backend Kubernetes
    location /api/ {
        proxy_pass http://backend-service:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Endpoint Prometheus de l'app
    location /metrics {
        proxy_pass http://backend-service:3000/metrics;
        proxy_set_header Host $host;
    }

    location ~* \.(js|css|png|jpg|gif|ico|svg|woff2)$ {
        expires 1d;
        add_header Cache-Control "public, no-transform";
    }
}